Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  config.vm.define "mgama" do |mg|
    mg.vm.hostname = "mgamaS"
    mg.vm.network "private_network", ip: "192.168.56.110"

    mg.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.linked_clone = true
    end

    mg.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get install -y curl

      export INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 \
        --advertise-address 192.168.56.110 \
        --node-ip 192.168.56.110 \
        --tls-san 192.168.56.110 \
        --flannel-iface=eth1"
      
      curl -sfL https://get.k3s.io | sh -

      while [ ! -f /var/lib/rancher/k3s/server/node-token ]; do sleep 2; done

      until curl -s -k https://192.168.56.110:6443/livez > /dev/null; do
        sleep 2
      done

      cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token

      kubectl apply -f /vagrant/manifest/
    SHELL
  end
end