Vagrant.configure("2") do |config|
  # Utilisation d'une box Debian 12 propre
  config.vm.box = "generic/debian12"

  config.vm.define "mgama" do |mg|
    mg.vm.hostname = "mgamaS"
    # Utilisation d'une IP sur une plage standard VirtualBox
    mg.vm.network "private_network", ip: "192.168.56.110"

    mg.vm.provider "virtualbox" do |vb|
      # IMPORTANT : K3s a besoin de minimum 1Go pour ne pas figer au boot
      vb.memory = 1024
      vb.cpus = 1
      vb.linked_clone = true
      # Activer l'interface graphique si tu veux voir où ça bloque
      # vb.gui = true 
    end

    mg.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get install -y curl
      export INSTALL_K3S_EXEC="--write-kubeconfig-mode 644 --bind-address 192.168.56.110 --node-ip 192.168.56.110 --flannel-iface=eth1"
      curl -sfL https://get.k3s.io | sh -
      
      # On attend que le token soit généré
      while [ ! -f /var/lib/rancher/k3s/server/node-token ]; do sleep 2; done
      cp /var/lib/rancher/k3s/server/node-token /vagrant/node-token
    SHELL
  end

  config.vm.define "mbrement" do |mb|
    mb.vm.hostname = "mbrementSW"
    mb.vm.network "private_network", ip: "192.168.56.111"

    mb.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.linked_clone = true
    end

    mb.vm.provision "shell", inline: <<-SHELL
      apt-get update && apt-get install -y curl
      while [ ! -f /vagrant/node-token ]; do sleep 2; done
      
      export K3S_URL="https://192.168.56.110:6443"
      export K3S_TOKEN=$(cat /vagrant/node-token)
      export INSTALL_K3S_EXEC="--node-ip 192.168.56.111 --flannel-iface=eth1"
      
      curl -sfL https://get.k3s.io | sh -
    SHELL
  end
end